name: Bug Report
description: Informez nous d'un bug.
title: "[Bug]: "
labels: ["bug"]
projects: ["WankulCrazy"]
body:
  - type: markdown
    attributes:
      value: |
        Merci d'avoir pris le temps de reporter un bug
  - type: textarea
    id: what-happened
    attributes:
      label: Que s'est-t-il passé ?
      description: Qu\'aurait-t-il dû se passer ?
      placeholder: Dites nous ce que vous voyer !
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: Quel version du mod était utilisée ?
      options:
        - 1.2.3 (Latest)
        - 1.2.2
        - 1.2.1
        - 1.2.0
        - 1.1.1
        - 1.1.0
        - 1.0.4
        - 1.0.3
        - 1.0.2
        - 1.0.1
        - 1.0.0
      default: 0
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logoutput BepInEx
      description: S\'il vous plait copiez le contenu dans BepInEx/LogOutput.log (essayez de prendre que la partie concernant les erreurs)
      render: shell
